config/routes.rb
KeywordStatistics::Application.routes.draw do

  resources :keywords

  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/keywords_controller.rb
require 'adwords_api'

class KeywordsController < ApplicationController
  def create
    # Convert submitted array of keywords to an Array
    keywords = params[:keywords].split(",")

    # Strip whitespace from the keywords
    keywords = keywords.collect(&:strip)

    # Remove empty keywords
    keywords = keywords.reject(&:empty?)

    # AdwordsApi is going to look for config file in ENV["HOME"]
    ENV["HOME"] = Rails.root.join("config").to_s
    adwords = AdwordsApi::Api.new
    tis = adwords.service(:CampaignService, :v201209)
    stuff = tis.get({:fields => ["Id", "Name"]})

    # Render keywords in JSON format
    render :text => stuff.inspect

    # TODO: Fallback if form was actually submitted (non-ajax)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= form_tag keywords_path, :id => "js_keywords_form" do %>
  <%= text_field_tag :keywords %>
  <%= submit_tag "Submit" %>
<% end %>

<ol id="js_keywords_list">

</ol>

<% content_for :javascripts do %>
<script type="text/javascript">
  $("#js_keywords_form").submit(function(e) {
    // Don't submit
    e.preventDefault()

    // AJAX request
    $.ajax({
      type: "POST",
      url: $(this).attr("action"),
      data: $(this).serialize(),
      success: function(data) {
        // Empty keywords list
        $("#js_keywords_list").html("")

        // Iterate through keywords and create <li>'s for them
        $.each(data, function() {
          $("#js_keywords_list").append($("<li>", {
            text: this
          }))
        })
      },
      error: function(error) {

      }
    })
  })
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdStage &middot; Keyword Statistics</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Keyword Statistics</h1>
  <%= yield %>

  <%= yield :javascripts %>
</body>
</html>